{{- with $.Values.vaultOperator.defaults }}
{{- $defaults := . }}
{{- with $.Values.vaultOperator.networks }}
{{- range $ingress := .ingress -}}
---
apiVersion: {{ default "networking.k8s.io/v1" $ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $ingress.name }}-ing
  namespace: {{ default (default (default $.Release.Namespace $defaults.namespace) .namespace ) .namespace }}
  {{- with .labels }}
  labels:
  {{- toYaml . | nindent 4 -}}
  {{ end }}
  {{- with .annotations }}
  annotations:
  {{- toYaml . | nindent 4 -}}
  {{ end }}
spec:
{{- with .spec }}
{{- toYaml . | nindent 2 }}
{{ end }}

{{ end }}
{{ end }}
{{ end }}